### ISSUE TITLE
Windowsでnpm installに失敗する

### ISSUE THREAD

**Issue by soeklgb** [Spoonail-Iroiro/maginai-game-types#10]
Windowsでnpm installをしたところ画像のようなエラーが出ました。

![log](https://github.com/Spoonail-Iroiro/maginai-game-types/assets/96245674/13fff28b-4388-4bf2-96f3-22afa87cfa63)

原因はnpm installの前に実行されるpackage.jsonのscripts.prepareのようで、シングルクォーテーションの代わりにエスケープされたダブルクォーテーションを使うと成功するようになりました。
（npm run prepare単体で実行するときはなぜかシングルクォーテーションでも成功します。）

prepareのhusky install以降は必須ではなさそうなので削除するのも良いかと思います。

**Comment by Spoonail-Iroiro** [comment]
>prepareのhusky install以降は必須ではなさそうなので削除するのも良いかと思います。

そうですね、削除しようと思います。
